################################################################################
# Library OpenThread (OT) Rules
################################################################################

OT_PLATFORM								= $(subst $\",,$(CONFIG_OPENTHREAD_PLATFORM))
ifneq (,$(filter $(CONFIG_OPENTHREAD_ENABLE_COMMISSIONER),y yes YES 1))
	LIB_CXXFLAGS += -DOPENTHREAD_ENABLE_COMMISSIONER=1
else
	LIB_CXXFLAGS += -DOPENTHREAD_ENABLE_COMMISSIONER=0
endif
ifneq (,$(filter $(CONFIG_OPENTHREAD_ENABLE_DTLS),y yes YES 1))
	LIB_CXXFLAGS += -DOPENTHREAD_ENABLE_DTLS=1
else
	LIB_CXXFLAGS += -DOPENTHREAD_ENABLE_DTLS=0
endif
ifneq (,$(filter $(CONFIG_OPENTHREAD_ENABLE_JOINER),y yes YES 1))
	LIB_CXXFLAGS += -DOPENTHREAD_ENABLE_JOINER=1
else
	LIB_CXXFLAGS += -DOPENTHREAD_ENABLE_JOINER=0
endif

LIB_CFLAGS += -DBYTE_ORDER_BIG_ENDIAN=0
LIB_CXXFLAGS += -DBYTE_ORDER_BIG_ENDIAN=0
#LIB_CFLAGS += -D_WIN32=0
#LIB_CXXFLAGS += -D_WIN32=0

LIBRARY_STACK_OPENTHREAD_SRC_DIR		= $(LIBRARY_STACK_OPENTHREAD_DIR)/src
LIBRARY_STACK_OPENTHREAD_EXAMPLES_DIR	= $(LIBRARY_STACK_OPENTHREAD_DIR)/examples
LIBRARY_STACK_OPENTHREAD_3RDPARTY_DIR	= $(LIBRARY_STACK_OPENTHREAD_DIR)/third_party

include $(LIBRARY_STACK_OPENTHREAD_SRC_DIR)/Makefile.mk
include $(LIBRARY_STACK_OPENTHREAD_EXAMPLES_DIR)/Makefile.mk
include $(LIBRARY_STACK_OPENTHREAD_3RDPARTY_DIR)/Makefile.mk

INC_PATH								+=										\
	$(LIBRARY_STACK_OPENTHREAD_DIR)/include										\
	$(LIBRARY_STACK_OPENTHREAD_DIR)/include/cli									\
	$(LIBRARY_STACK_OPENTHREAD_DIR)/include/commissioning						\
	$(LIBRARY_STACK_OPENTHREAD_DIR)/include/ncp									\
	$(LIBRARY_STACK_OPENTHREAD_DIR)/include/platform