################################################################################
# Library OpenThread (OT) - SRC/CORE Rules
################################################################################

LIBRARY_STACK_OPENTHREAD_SRC_CORE_COAP_DIR		= $(LIBRARY_STACK_OPENTHREAD_SRC_CORE_DIR)/coap
LIBRARY_STACK_OPENTHREAD_SRC_CORE_COMMON_DIR	= $(LIBRARY_STACK_OPENTHREAD_SRC_CORE_DIR)/common
LIBRARY_STACK_OPENTHREAD_SRC_CORE_CRYPTO_DIR	= $(LIBRARY_STACK_OPENTHREAD_SRC_CORE_DIR)/crypto
LIBRARY_STACK_OPENTHREAD_SRC_CORE_MAC_DIR		= $(LIBRARY_STACK_OPENTHREAD_SRC_CORE_DIR)/mac
LIBRARY_STACK_OPENTHREAD_SRC_CORE_MESHCOP_DIR	= $(LIBRARY_STACK_OPENTHREAD_SRC_CORE_DIR)/meshcop
LIBRARY_STACK_OPENTHREAD_SRC_CORE_NET_DIR		= $(LIBRARY_STACK_OPENTHREAD_SRC_CORE_DIR)/net
LIBRARY_STACK_OPENTHREAD_SRC_CORE_THREAD_DIR	= $(LIBRARY_STACK_OPENTHREAD_SRC_CORE_DIR)/thread

LIB_CPPSRC								+=										\
	$(LIBRARY_STACK_OPENTHREAD_SRC_CORE_DIR)/openthread.cpp

include $(LIBRARY_STACK_OPENTHREAD_SRC_CORE_COAP_DIR)/Makefile.mk
include $(LIBRARY_STACK_OPENTHREAD_SRC_CORE_COMMON_DIR)/Makefile.mk
include $(LIBRARY_STACK_OPENTHREAD_SRC_CORE_CRYPTO_DIR)/Makefile.mk
include $(LIBRARY_STACK_OPENTHREAD_SRC_CORE_MAC_DIR)/Makefile.mk
include $(LIBRARY_STACK_OPENTHREAD_SRC_CORE_MESHCOP_DIR)/Makefile.mk
include $(LIBRARY_STACK_OPENTHREAD_SRC_CORE_NET_DIR)/Makefile.mk
include $(LIBRARY_STACK_OPENTHREAD_SRC_CORE_THREAD_DIR)/Makefile.mk

INC_PATH								+=										\
	$(LIBRARY_STACK_OPENTHREAD_SRC_CORE_DIR)
