################################################################################
# Library OpenThread (OT) - SRC Rules
################################################################################

LIBRARY_STACK_OPENTHREAD_SRC_CLI_DIR		= $(LIBRARY_STACK_OPENTHREAD_SRC_DIR)/cli
LIBRARY_STACK_OPENTHREAD_SRC_CORE_DIR		= $(LIBRARY_STACK_OPENTHREAD_SRC_DIR)/core
LIBRARY_STACK_OPENTHREAD_SRC_DIAG_DIR		= $(LIBRARY_STACK_OPENTHREAD_SRC_DIR)/diag
LIBRARY_STACK_OPENTHREAD_SRC_MISSING_DIR	= $(LIBRARY_STACK_OPENTHREAD_SRC_DIR)/missing
LIBRARY_STACK_OPENTHREAD_SRC_NCP_DIR		= $(LIBRARY_STACK_OPENTHREAD_SRC_DIR)/ncp

include $(LIBRARY_STACK_OPENTHREAD_SRC_CLI_DIR)/Makefile.mk
include $(LIBRARY_STACK_OPENTHREAD_SRC_CORE_DIR)/Makefile.mk
include $(LIBRARY_STACK_OPENTHREAD_SRC_DIAG_DIR)/Makefile.mk
#include $(LIBRARY_STACK_OPENTHREAD_SRC_MISSING_DIR)/Makefile.mk
include $(LIBRARY_STACK_OPENTHREAD_SRC_NCP_DIR)/Makefile.mk